# Script PowerShell per creare i label secondari
gh label create models --color "006b75" --description "Domain models"
gh label create pattern --color "fbca04" --description "Design patterns"
gh label create "thread-safety" --color "b60205" --description "Thread safety e concorrenza"
gh label create security --color "d93f0b" --description "Sicurezza"
gh label create endpoints --color "0e8a16" --description "API endpoints"
gh label create feature --color "1d76db" --description "Nuove funzionalità"
gh label create metrics --color "c5def5" --description "Metriche e KPI"
gh label create background --color "ffd700" --description "Processi in background"
gh label create performance --color "ff69b4" --description "Performance e ottimizzazioni"
gh label create quality --color "d93f0b" --description "Qualità del codice"
gh label create integration --color "d4c5f9" --description "Test di integrazione"
gh label create docker --color "000000" --description "Docker e containerizzazione"
gh label create kubernetes --color "000000" --description "Kubernetes"
