# Script PowerShell per creare i label
gh label create setup --color "0366d6" --description "Setup e configurazione iniziale"
gh label create database --color "5319e7" --description "Database e persistenza dati"
gh label create domain --color "006b75" --description "Domain models e logica di business"
gh label create infrastructure --color "fbca04" --description "Infrastruttura e configurazione"
gh label create console --color "1d76db" --description "Console UI e interazioni"
gh label create authentication --color "b60205" --description "Autenticazione e sicurezza"
gh label create ui --color "0052cc" --description "User Interface"
gh label create api --color "0e8a16" --description "API endpoints e servizi"
gh label create search --color "5319e7" --description "Funzionalità di ricerca"
gh label create logging --color "d4c5f9" --description "Logging e diagnostica"
gh label create monitoring --color "c5def5" --description "Monitoring e metriche"
gh label create jobs --color "ffd700" --description "Background jobs e tasks"
gh label create cache --color "ff69b4" --description "Caching e performance"
gh label create testing --color "d93f0b" --description "Testing e qualità"
gh label create deployment --color "000000" --description "Deployment e distribuzione"
gh label create "priority:high" --color "b60205" --description "Alta priorità"
gh label create "priority:medium" --color "fbca04" --description "Media priorità"
gh label create "priority:low" --color "0e8a16" --description "Bassa priorità"
